{% macro calc_wakuban(total_horses, umaban) %}
CASE
    WHEN {{ total_horses }} <= 8 THEN {{ umaban }}
    WHEN {{ total_horses }} = 9 THEN
        CASE WHEN {{ umaban }} <= 7 THEN {{ umaban }}
             WHEN {{ umaban }} <= 9 THEN 8 END
    WHEN {{ total_horses }} = 10 THEN
        CASE WHEN {{ umaban }} <= 6 THEN {{ umaban }}
             WHEN {{ umaban }} <= 8 THEN 7
             WHEN {{ umaban }} <= 10 THEN 8 END
    WHEN {{ total_horses }} = 11 THEN
        CASE WHEN {{ umaban }} <= 5 THEN {{ umaban }}
             WHEN {{ umaban }} <= 7 THEN 6
             WHEN {{ umaban }} <= 9 THEN 7
             WHEN {{ umaban }} <= 11 THEN 8 END
    WHEN {{ total_horses }} = 12 THEN
        CASE WHEN {{ umaban }} <= 4 THEN {{ umaban }}
             WHEN {{ umaban }} <= 6 THEN 5
             WHEN {{ umaban }} <= 8 THEN 6
             WHEN {{ umaban }} <= 10 THEN 7
             WHEN {{ umaban }} <= 12 THEN 8 END
    WHEN {{ total_horses }} = 13 THEN
        CASE WHEN {{ umaban }} <= 3 THEN {{ umaban }}
             WHEN {{ umaban }} <= 5 THEN 4
             WHEN {{ umaban }} <= 7 THEN 5
             WHEN {{ umaban }} <= 9 THEN 6
             WHEN {{ umaban }} <= 11 THEN 7
             WHEN {{ umaban }} <= 13 THEN 8 END
    WHEN {{ total_horses }} = 14 THEN
        CASE WHEN {{ umaban }} <= 2 THEN {{ umaban }}
             WHEN {{ umaban }} <= 4 THEN 3
             WHEN {{ umaban }} <= 6 THEN 4
             WHEN {{ umaban }} <= 8 THEN 5
             WHEN {{ umaban }} <= 10 THEN 6
             WHEN {{ umaban }} <= 12 THEN 7
             WHEN {{ umaban }} <= 14 THEN 8 END
    WHEN {{ total_horses }} = 15 THEN
        CASE WHEN {{ umaban }} <= 1 THEN {{ umaban }}
             WHEN {{ umaban }} <= 3 THEN 2
             WHEN {{ umaban }} <= 5 THEN 3
             WHEN {{ umaban }} <= 7 THEN 4
             WHEN {{ umaban }} <= 9 THEN 5
             WHEN {{ umaban }} <= 11 THEN 6
             WHEN {{ umaban }} <= 13 THEN 7
             WHEN {{ umaban }} <= 15 THEN 8 END
    WHEN {{ total_horses }} = 16 THEN
        CASE WHEN {{ umaban }} <= 2 THEN 1
             WHEN {{ umaban }} <= 4 THEN 2
             WHEN {{ umaban }} <= 6 THEN 3
             WHEN {{ umaban }} <= 8 THEN 4
             WHEN {{ umaban }} <= 10 THEN 5
             WHEN {{ umaban }} <= 12 THEN 6
             WHEN {{ umaban }} <= 14 THEN 7
             WHEN {{ umaban }} <= 16 THEN 8 END
    WHEN {{ total_horses }} = 17 THEN
        CASE WHEN {{ umaban }} <= 2 THEN 1
             WHEN {{ umaban }} <= 4 THEN 2
             WHEN {{ umaban }} <= 6 THEN 3
             WHEN {{ umaban }} <= 8 THEN 4
             WHEN {{ umaban }} <= 10 THEN 5
             WHEN {{ umaban }} <= 12 THEN 6
             WHEN {{ umaban }} <= 14 THEN 7
             WHEN {{ umaban }} <= 17 THEN 8 END
    WHEN {{ total_horses }} = 18 THEN
        CASE WHEN {{ umaban }} <= 2 THEN 1
             WHEN {{ umaban }} <= 4 THEN 2
             WHEN {{ umaban }} <= 6 THEN 3
             WHEN {{ umaban }} <= 8 THEN 4
             WHEN {{ umaban }} <= 10 THEN 5
             WHEN {{ umaban }} <= 12 THEN 6
             WHEN {{ umaban }} <= 15 THEN 7
             WHEN {{ umaban }} <= 18 THEN 8 END
    ELSE NULL
END
{% endmacro %}
