{{ config(
    materialized='view',
    schema='api'
) }}

SELECT v55.race_date,                                                                                                                                                                                     
     v55.venue_code,                                                                                                                                                                                        
     v55.race_no,                                                                                                                                                                                           
     v55.umaban,                                                                                                                                                                                            
     v55.horse_id,                                                                                                                                                                                          
     v55.horse_name,                                                                                                                                                                                        
     v55.jockey_code,                                                                                                                                                                                       
     v55.trainer_code,                                                                                                                                                                                      
     v55.gate_no,                                                                                                                                                                                           
     v55.score_idm,                                                                                                                                                                                         
     v55.idx_ten,                                                                                                                                                                                           
     v55.idx_agari,                                                                                                                                                                                         
     v55.odds_win_pre,                                                                                                                                                                                      
     v55.pop_win_pre,                                                                                                                                                                                       
     v55.distance_m,                                                                                                                                                                                        
     v55.total_horses,                                                                                                                                                                                      
     v55.class_code_num,                                                                                                                                                                                    
     v55.is_hurdle,                                                                                                                                                                                         
     v55.surface_type,                                                                                                                                                                                      
     v55.idm_zscore,                                                                                                                                                                                        
     v55.ten_zscore,                                                                                                                                                                                        
     v55.agari_zscore,                                                                                                                                                                                      
     v55.race_std_idm,                                                                                                                                                                                      
     v55.race_std_ten,                                                                                                                                                                                      
     v55.race_std_agari,                                                                                                                                                                                    
     v55.tyb_total_score,                                                                                                                                                                                   
     v55.tyb_track_cond,                                                                                                                                                                                    
     v55.jvd_cushion_val,                                                                                                                                                                                   
     v55.sire_system_code,                                                                                                                                                                                  
     v55.bms_system_code,                                                                                                                                                                                   
     v55.gekiso_index,                                                                                                                                                                                      
     v55.dist_aptitude,                                                                                                                                                                                     
     v55.stable_eval_code,                                                                                                                                                                                  
     v55.training_arrow_code,                                                                                                                                                                               
     v55.gekiso_dist_cross,                                                                                                                                                                                 
     v55.training_stable_cross,                                                                                                                                                                             
     v55.grass_aptitude_code,                                                                                                                                                                               
     v55.dirt_aptitude_code,                                                                                                                                                                                
     v55.running_style_code,                                                                                                                                                                                
     v55.mud_aptitude_code,                                                                                                                                                                                 
     v55.running_form_code,                                                                                                                                                                                 
     v55.body_type_code,                                                                                                                                                                                    
     v55.rotation_days,                                                                                                                                                                                     
     v55.dist_aptitude2,                                                                                                                                                                                    
     v55.longshot_index,                                                                                                                                                                                    
     v55.start_index,                                                                                                                                                                                       
     v55.late_start_rate,                                                                                                                                                                                   
     v55.popular_index,                                                                                                                                                                                     
     v55.jockey_exp_rentai,                                                                                                                                                                                 
     v55.jockey_exp_win,                                                                                                                                                                                    
     v55.jockey_exp_top3,                                                                                                                                                                                   
     v55.track_fit_signal,                                                                                                                                                                                  
     v55.tt_bias_score,                                                                                                                                                                                     
     v55.tt_alpha_signal,                                                                                                                                                                                   
     v55.tt_confidence,                                                                                                                                                                                     
     v55.tt_video_count,                                                                                                                                                                                    
     v55.low_pop_high_idm,                                                                                                                                                                                  
     v55.pace_advantage_score,                                                                                                                                                                              
     v55.actual_rank,                                                                                                                                                                                       
     v55.is_winner,                                                                                                                                                                                         
     v55.is_top3,                                                                                                                                                                                           
     v55.rank_ratio,                                                                                                                                                                                        
     v55.rotation_seg,                                                                                                                                                                                      
     v55.gate_style_cross,                                                                                                                                                                                  
     v55.gate_bias_score,                                                                                                                                                                                   
     v55.dist_category,                                                                                                                                                                                     
     v55.gate_style_dist_cross,                                                                                                                                                                             
     v55.style_rotation_cross,                                                                                                                                                                              
     v55.short_rest_high_idm,                                                                                                                                                                               
     v55.tt_idm_cross,                                                                                                                                                                                      
     v55.tyb_paddock_score,                                                                                                                                                                                 
     v55.tyb_horse_weight,                                                                                                                                                                                  
     v55.tyb_weight_change,                                                                                                                                                                                 
     v55.tyb_vibe_code,                                                                                                                                                                                     
     v55.tyb_jockey_score,                                                                                                                                                                                  
     v55.tyb_info_score,                                                                                                                                                                                    
     v55.tyb_odds_score,                                                                                                                                                                                    
     v55.tyb_cho_total_mark,                                                                                                                                                                                
     v55.tyb_idm,                                                                                                                                                                                           
     v55.tyb_win_odds,                                                                                                                                                                                      
     v55.tyb_place_odds,                                                                                                                                                                                    
     v55.tyb_equipment_change,                                                                                                                                                                              
     v55.tyb_leg_info,                                                                                                                                                                                      
     v55.tyb_body_code,                                                                                                                                                                                     
     v55.h1_bias_score,                                                                                                                                                                                     
     v55.h1_alpha_signal,                                                                                                                                                                                   
     v55.h1_confidence,                                                                                                                                                                                     
     v55.h1_video_count,                                                                                                                                                                                    
     v55.feat_vg_fu2,                                                                                                                                                                                       
     v55.feat_vg_yusen,                                                                                                                                                                                     
     v55.feat_vg_f_index,                                                                                                                                                                                   
     v55.h1_idm_cross,                                                                                                                                                                                      
     v55.moe_regime,                                                                                                                                                                                        
     COALESCE(cu.feat_causal_jockey_change, 0) AS feat_causal_jockey_change,                                                                                                                                
     COALESCE(cu.feat_causal_short_interval, 0) AS feat_causal_short_interval,                                                                                                                              
     COALESCE(da.feat_deriv_idm_delta, (0)::numeric) AS feat_deriv_idm_delta,                                                                                                                               
     COALESCE(da.feat_deriv_ten_delta, (0)::numeric) AS feat_deriv_ten_delta,                                                                                                                               
     COALESCE(da.feat_deriv_agari_delta, (0)::numeric) AS feat_deriv_agari_delta,                                                                                                                           
     COALESCE(da.feat_deriv_improving, 0) AS feat_deriv_improving,                                                                                                                                          
     (0)::numeric AS feat_blood_sire_cond_top3,
     0 AS feat_blood_sire_cond_sample,
     0 AS feat_blood_sire_hot_cond,
     (0)::numeric AS feat_sf_speed_figure,
     (0)::numeric AS feat_tb_inner_bias                                                                                                                                    
FROM {{ ref('v_inference_today_v55') }} v55                                                                                                                                                               
LEFT JOIN api.mv_causal_uplift_features cu ON (((v55.race_date = cu.race_date) AND (v55.venue_code = cu.venue_code) AND (lpad(v55.race_no::text, 2, '0'::text) = cu.race_no) AND (v55.umaban = cu.umaban::text)))
LEFT JOIN api.mv_derivative_alpha da ON (((v55.race_date = da.race_date) AND (v55.venue_code = da.venue_code) AND (lpad(v55.race_no::text, 2, '0'::text) = da.race_no) AND (v55.umaban = da.umaban::text)))      
